# Generated by Django 5.1.7 on 2025-03-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="flavor_review",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="servings",
            field=models.IntegerField(default=1),
        ),
    ]
