name: Flutter Android CD
on:
  push:
    branches: ["main", "develop"]
jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.29.0
      - name: Generate .env
        run: echo "${{ secrets.ENV }}" | base64 --decode > .env
        working-directory: client
      - name: Generate firebase_options.dart
        run: echo "${{ secrets.FIREBASE_OPTIONS_DART }}" | base64 --decode > lib/firebase_options.dart
        working-directory: client
      - name: Generate google-services.json
        run: echo "${{ secrets.GOOGLE_SERVICE_JSON }}" | base64 --decode > android/app/google-services.json
        working-directory: client
      - name: Install dependencies
        run: flutter pub get
        working-directory: client
      - name: Run build_runner
        run: dart run build_runner build --delete-conflicting-outputs
        working-directory: client
      - name: Build Android APK
        run: flutter build apk --release
        working-directory: client
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: terraform-gcp-learning-yo2
      - name: Authenticate with service account
        run: |
          echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" | base64 --decode > key.json
          gcloud auth activate-service-account --key-file=key.json
      - name: Upload file to Google Cloud Storage
        run: gcloud storage cp build/app/outputs/flutter-apk/app-release.apk gs://terraform-gcp-learning-yo2-deploy-bucket
        working-directory: client
