name: Flutter Android CD
on:
  push:
    branches: ["main", "develop"]
jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.29.0
      - run: flutter pub get
        working-directory: client
      - name: Build Android APK
        run: flutter build apk --release
        working-directory: client
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: flutter-web-deploy-learning
      - name: Authenticate with service account
        run: |
          echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" | base64 --decode > key.json
          gcloud auth activate-service-account --key-file=key.json
      - name: Upload file to Google Cloud Storage
        run: gcloud storage cp build/app/outputs/flutter-apk/app-release.apk gs://flutter-web-deploy-learning.firebasestorage.app
        working-directory: client
